name: komhack2026_late_permt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  http: ^1.2.0
  connectivity_plus: ^7.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  permission_handler: ^12.0.1
  audioplayers: ^6.6.0
  firebase_messaging: ^16.1.3
  flutter_local_notifications: ^21.0.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - images/logo.png
    - assets/icon/app_icon.png
    - assets/sounds/alert1.mp3

# launcher icon config (outside flutter block)
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

  # optional but recommended for modern android icons
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"