// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYP88PwNQOWZJ6guN6OIuUmheYSUF6s4s',
    appId: '1:894898304439:web:7fd17e3b5ace1d1fc62432',
    messagingSenderId: '894898304439',
    projectId: 'komhack26-late-permt',
    authDomain: 'komhack26-late-permt.firebaseapp.com',
    storageBucket: 'komhack26-late-permt.firebasestorage.app',
    measurementId: 'G-6CHEPE1R5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApXBKZWFFMnS2EDLdpR6kpG8xTaQUgYvA',
    appId: '1:894898304439:android:7badc352be8727b6c62432',
    messagingSenderId: '894898304439',
    projectId: 'komhack26-late-permt',
    storageBucket: 'komhack26-late-permt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXGW8CTNGmUy4nB8cPrOwoMU2o_sCnmzo',
    appId: '1:894898304439:ios:243760d4e9a714d9c62432',
    messagingSenderId: '894898304439',
    projectId: 'komhack26-late-permt',
    storageBucket: 'komhack26-late-permt.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKZ8BQ7CnXHcdJwOPOWKt_QwldiC5MOY0',
    appId: '1:894898304439:ios:243760d4e9a714d9c62432',
    messagingSenderId: '894898304439',
    projectId: 'komhack26-late-permt',
    storageBucket: 'komhack26-late-permt.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYP88PwNQOWZJ6guN6OIuUmheYSUF6s4s',
    appId: '1:894898304439:web:957383e425298ff4c62432',
    messagingSenderId: '894898304439',
    projectId: 'komhack26-late-permt',
    authDomain: 'komhack26-late-permt.firebaseapp.com',
    storageBucket: 'komhack26-late-permt.firebasestorage.app',
    measurementId: 'G-SHTCXH5G2K',
  );
}